# Generated by Django 5.0.6 on 2024-06-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_streamingplatform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingplatform',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
