# Generated by Django 5.0.6 on 2024-07-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0009_movie_avg_review_movie_num_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='avg_review',
        ),
    ]
