# Generated by Django 5.0.6 on 2024-07-25 19:54

import django.db.models.aggregates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0010_remove_movie_avg_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_review',
            field=models.FloatField(default=0, verbose_name=django.db.models.aggregates.Avg('rating')),
        ),
    ]
