# Generated by Django 5.0.6 on 2024-07-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0011_movie_avg_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='avg_review',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='num_reviews',
        ),
    ]
