# Generated by Django 5.0.6 on 2024-08-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0012_remove_movie_avg_review_remove_movie_num_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=60),
        ),
    ]
